name: CI Pipeline

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Fix files permissions
        run: |
          chmod +x node_modules/.bin/eslint
          chmod +x node_modules/.bin/prettier
          chmod +x node_modules/.bin/jest

      - name: Run linter
        run: npm run lint

      - name: Run formatter
        run: npm run prettier -- --check .

      - name: Run tests
        run: CI=true npm test

      - name: Build project
        run: npm run build
