name: CI Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run formatter
        run: npm run prettier -- --check .

      - name: Run tests
        run: CI=true npm test

      - name: Build project
        run: npm run build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init & Apply
        id: tf_apply
        working-directory: ./infra
        run: |
          terraform init
          terraform apply -auto-approve
        env:
          TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
          TF_VAR_ssh_fingerprint: ${{ secrets.SSH_FINGERPRINT }}

      - name: Get Droplet Public IP
        id: get_ip
        working-directory: ./infra
        run: |
          ip=$(terraform output -raw ip_address)
          echo "D_O_PUBLIC_IP=$ip" >> $GITHUB_ENV

      - name: Run JMeter load test
        run: |
          sudo apt update && sudo apt install -y openjdk-11-jre-headless unzip
          curl -L https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.5.zip -o jmeter.zip
          unzip jmeter.zip
          apache-jmeter-5.5/bin/jmeter -n -t ./jmeter/load-test.jmx -Jserver_url=http://$D_O_PUBLIC_IP -l result.jtl -e -o report

      - name: Upload JMeter HTML report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-report
          path: report
